### ISSUE TITLE
Stil Not working in Gome-Shell 3.10

### ISSUE THREAD

**Issue by mightymouse2045** [bmh1980/gnome-shell-extension-searchbookmarks#4]
Getting this error:

Gjs-Message: JS LOG: A TypeError has occured in undefined: this.searchSystem.pushResults is not a function
