### ISSUE TITLE
Stil Not working in Gome-Shell 3.10

### ISSUE THREAD

**Issue by mightymouse2045** [bmh1980/gnome-shell-extension-searchbookmarks#6]
Sorry to be the bearer of bad news:

(gnome-shell:22830): Gjs-WARNING **: JS ERROR: Exception in callback for signal: search-updated: TypeError: provider.createResultObject is not a function
GridSearchResult<._init@/usr/share/gnome-shell/js/ui/searchDisplay.js:129
wrapper@/usr/share/gjs-1.0/lang.js:213
_Base._construct@/usr/share/gjs-1.0/lang.js:154
Class._construct/newClass@/usr/share/gjs-1.0/lang.js:248
GridSearchResults<._renderResults@/usr/share/gnome-shell/js/ui/searchDisplay.js:330
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchResultsBase<.updateSearch/<@/usr/share/gnome-shell/js/ui/searchDisplay.js:244
SearchBookmarks<.getResultMetas@/home/ph/.local/share/gnome-shell/extensions/searchbookmarks@bmh1980de.gmail.com/extension.js:198
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchResultsBase<.updateSearch@/usr/share/gnome-shell/js/ui/searchDisplay.js:236
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchResults<._updateResults@/usr/share/gnome-shell/js/ui/searchDisplay.js:503
wrapper@/usr/share/gjs-1.0/lang.js:213
_emit@/usr/share/gjs-1.0/signals.js:124
SearchSystem<.setResults@/usr/share/gnome-shell/js/ui/search.js:60
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchBookmarks<.getInitialResultSet@/home/ph/.local/share/gnome-shell/extensions/searchbookmarks@bmh1980de.gmail.com/extension.js:170
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchBookmarks<.getSubsearchResultSet@/home/ph/.local/share/gnome-shell/extensions/searchbookmarks@bmh1980de.gmail.com/extension.js:177
wrapper@/usr/share/gjs-1.0/lang.js:213
SearchSystem<.updateSearchResults@/usr/share/gnome-shell/js/ui/search.js:87
wrapper@/usr/share/gjs-1.0/lang.js:213
ViewSelector<._doSearch@/usr/share/gnome-shell/js/ui/viewSelector.js:489
wrapper@/usr/share/gjs-1.0/lang.js:213

**Comment by bmh1980** [comment]
Since I haven’t access to 3.10 I can’t test my changes. :-( And before I push my new changes, can you please test them?

You have only to change the name of a method. Change line 155 in extension.js from 'createResultActor: function(resultMeta, terms) {' to 'createResultObject: function(resultMeta, terms) {'.

IF the GNOME developers haven’t changed more, this should work.

**Comment by mightymouse2045** [comment]
yes that works and searching bookmarks works now with that change and installing works now as well with your makefile changes :)
